### ISSUE TITLE
Catalina installer firmware update required

### ISSUE THREAD

**Issue by josemmc95** [dortania/vanilla-laptop-guide#13]
I followed the guide for macOS Catalina and a Syklake laptop, Asus X556U.

When I format the drive to APFS, it says I can't choose this drive because I need an update for my Mac firmware and it recommends me to choose Mac OS Plus (Journaled).

I formatted with Mac OS Plus (Journaled) and when it restarts (suddenly), it says that an error occurred verifying the firmware.

Does anyone know how to fix it?

Thank you in advance.

**Comment by khronokernel** [comment]
This is actually a bug recently fixed in OpenCore 0.5.8 with the merge of ApfsDriverLoader into it, so while not ideal but wait till Monday and both the guide and OpenCore's release should be updated to official 0.5.8 support.

If you're a bit more technically inclined and are able to compile OpenCore, the [Configuration.pdf](https://github.com/acidanthera/OpenCorePkg/blob/master/Docs/Configuration.pdf) has all the necessary info
