### ISSUE TITLE
HDMI audio

### ISSUE THREAD

**Issue by sahebcrazy** [dortania/vanilla-laptop-guide#35]
I just finished setting up catalina on kabylake-r. Thanks for everything. But my HDMI codec is detected by the system but not showing in output device. And my display brightness keys not working.

**Comment by onoakino** [comment]
Hi. Thank you for the wonderful Open Core Desktop guide! Sorry if this comment's off-topic but while reading thru the guide on configuring Intel USB Mapping, the great Rehabman was mentioned very briefly. I am deeply troubled and couldn't continue reading the rest of the tutorial. The forum that he maintained about elitebooks has been abandoned since Mojave. Is it really true that he's gone for good? Has he passed away already? :(

**Comment by khronokernel** [comment]
No specs or further info given, closing
